package com.example.chucknorrisapp.pogo;

import java.util.List;

//POJO class generated by https://www.jsonschema2pojo.org for https://api.icndb.com/jokes/random/3
public class Joke {

    @com.squareup.moshi.Json(name = "type")
    private String type;
    @com.squareup.moshi.Json(name = "value")
    private List<Value> value = null;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public List<Value> getValue() {
        return value;
    }

    public void setValue(List<Value> value) {
        this.value = value;
    }

}
